# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QTextCharFormat
from PyQt5.QtCore import Qt, QDate


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #사진 저장
        self.image_save = QtWidgets.QPushButton(self.centralwidget)
        self.image_save.setGeometry(QtCore.QRect(720, 529, 101, 41))
        self.image_save.setObjectName("image_save")

        #암 등급 예측
        self.image_cancer_predict = QtWidgets.QPushButton(self.centralwidget)
        self.image_cancer_predict.setGeometry(QtCore.QRect(500, 529, 101, 41))
        self.image_cancer_predict.setObjectName("image_cancer_predict")

        #암세포 에측
        self.image_search_cancer = QtWidgets.QPushButton(self.centralwidget)
        self.image_search_cancer.setGeometry(QtCore.QRect(610, 529, 101, 41))
        self.image_search_cancer.setObjectName("image_search_cancer")

        #암 등급 예측 값
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(330, 529, 161, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        
        # 사진 보여주는 창
        self.image_view = QtWidgets.QLabel(self.centralwidget)
        self.image_view.setGeometry(QtCore.QRect(330, 20, 491, 491))
        self.image_view.setObjectName("label")
        #달력
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 7, 291, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        # 달력 오늘 날짜
        calendar_today_style = QTextCharFormat()
        calendar_today_style.setForeground(Qt.red)
        calendar_today_style.setBackground(Qt.yellow)
        self.calendarWidget.setDateTextFormat(QDate.currentDate(), calendar_today_style)

        #달력 action
        self.calendarWidget.clicked.connect(self.calendar_date)
        # self.select_day = self.calendarWidget.selectedDate()
        #환자 목록 새로고침
        self.re_patient_list = QtWidgets.QPushButton(self.centralwidget)
        self.re_patient_list.setGeometry(QtCore.QRect(240, 360, 71, 31))
        self.re_patient_list.setObjectName("re_patient_list")
        self.re_patient_list.clicked.connect(self.startFound)
        #환자 검색
        self.search_patient = QtWidgets.QPushButton(self.centralwidget)
        self.search_patient.setGeometry(QtCore.QRect(160, 360, 71, 31))
        self.search_patient.setObjectName("search_patient")
        #결과 보여주는 창
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 360, 131, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.patient_list = QtWidgets.QTreeView(self.centralwidget)
        self.patient_list.setGeometry(QtCore.QRect(20, 190, 291, 161))
        self.patient_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_list.setObjectName("patient_list")
        self.patient_list.setRootIsDecorated(False)
        self.patient_list.setAlternatingRowColors(True)

        self.info = QStandardItemModel(0,3,self)
        self.info.setHeaderData(0, Qt.Horizontal, "환자번호")
        self.info.setHeaderData(1, Qt.Horizontal, "  이   름")
        self.info.setHeaderData(2, Qt.Horizontal, "생년월일")

        self.patient_list.setModel(self.info)
        self.patient_list.setColumnWidth(0, 60)
        self.patient_list.setColumnWidth(1, 60)
        self.patient_list.setColumnWidth(2, 60)

        self.patient_list.clicked.connect(self.find_patient_image_list)


        self.patient_image = QtWidgets.QTreeView(self.centralwidget)
        self.patient_image.setGeometry(QtCore.QRect(20, 401, 291, 171))
        self.patient_image.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_image.setObjectName("patient_cancer_image")
        self.patient_image.setRootIsDecorated(False)
        self.patient_image.setAlternatingRowColors(True)

        self.info_image = QStandardItemModel(0, 3, self)
        self.info_image.setHeaderData(0, Qt.Horizontal, "검사일")
        self.info_image.setHeaderData(1, Qt.Horizontal, "파일명")
        self.info_image.setHeaderData(2, Qt.Horizontal, "기타")

        self.patient_image.setModel(self.info_image)
        self.patient_image.setColumnWidth(0, 60)
        self.patient_image.setColumnWidth(1, 150)
        self.patient_image.setColumnWidth(2, 60)

        self.patient_image.clicked.connect(self.show_patient_image)



        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_save.setText(_translate("MainWindow", "Save"))
        self.image_cancer_predict.setText(_translate("MainWindow", "Prediction"))
        self.image_search_cancer.setText(_translate("MainWindow", "Search"))
        self.re_patient_list.setText(_translate("MainWindow", "새로고침"))
        self.search_patient.setText(_translate("MainWindow", "검 색"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
