
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        
        Frame.setObjectName("Frame")
        Frame.resize(472, 459)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 50, 101, 91))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Frame)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 160, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 50, 241, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(100, 90, 241, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(20, 60, 56, 12))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 56, 12))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Frame)
        self.radioButton.setGeometry(QtCore.QRect(10, 250, 90, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Frame)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 250, 90, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Frame)
        self.radioButton_3.setGeometry(QtCore.QRect(230, 250, 90, 16))
        self.radioButton_3.setObjectName("radioButton_3")

        self.retranslateUi(Frame)
        self.radioButton.clicked.connect(Frame.setCycle)
        self.radioButton_2.clicked.connect(Frame.setCycle)
        self.radioButton_3.clicked.connect(Frame.setCycle)
        self.pushButton.clicked.connect(Frame.startchk)
        self.pushButton_2.clicked.connect(Frame.stopchk)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton.setText(_translate("Frame", "Login"))
        self.pushButton_2.setText(_translate("Frame", "Exit"))
        self.label.setText(_translate("Frame", "ID"))
        self.label_2.setText(_translate("Frame", "PW"))
        self.radioButton.setText(_translate("Frame", "10초"))
        self.radioButton_2.setText(_translate("Frame", "5분"))
        self.radioButton_3.setText(_translate("Frame", "10분"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
